epochs: 400
batch_size: 8
lr: 5.0e-4
wd: 5.0e-4
height: 60
width: 96
test_freq: 20

hidden_channels: 32
embedding_size: 32
num_heads: 8
in_len: 12
out_len: 12
missing_ratio: 0.5

target_strategy: "random"
